### ISSUE TITLE
How do I add tint? 

### ISSUE THREAD

**Issue by NoamEfergan** [exyte/SVGView#33]
Hey, great package and works perfectly for me, but I can't seem to be able to tint the SVGs that I'm downloading from the CDN, is that something that's missing or do I just not know how to do ?

**Comment by ystrot** [comment]
Hey @NoamEfergan,

Since `SVGView` is just a regular SwiftUI view, you can use [common techniques](https://www.hackingwithswift.com/books/ios-swiftui/special-effects-in-swiftui-blurs-blending-and-more) to add a tint.

Moreover, since you have control of a SVG tree, you can use some custom function to adjust SVG as you need. For example, the following function replace color of all shapes with a specified one:
```Swift
func tint(_ node: SVGNode, color: SVGColor) {
    if let group = node as? SVGGroup {
        for content in group.contents {
            tint(content, color: color)
        }
    } else if let shape = node as? SVGShape {
        shape.fill = color
    }
}
```

You can apply it to the whole SVG using following snippet:
```Swift
let view = SVGView(...)
tint(view.svg!, color: SVGColor(0xFF0000))
```

**Comment by NoamEfergan** [comment]
Thank you for the amazingly quick reply! 
the code you provided to tint recursively works perfectly for me, thanks a lot!
